---
galaxy_info:
  role_name: influxdb
  author: Travis Holton
  description: Install and configure Influx DB
  company: Catalyst
  license: BSD

  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
      - 7
    - name: Ubuntu
      versions:
      - bionic
      - xenial

  galaxy_tags: ['influxdb', 'monitoring']

dependencies: []
