---
- name: Configure FireWall | Open port prometheus-server
  firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled

- name: Configure FireWall | Restart firewalld
  systemd:
    name: firewalld
    state: reloaded
