- name: Install some python dependencies
  pip:
    name:
      - requests
      - influxdb
    state: present

- name: Start influxd
  service:
    name: influxd
    state: started

- name: Wait for a connection on influxdb port
  wait_for:
    host: localhost
    port: 8086

- name: Create InfluxDB DataBase
  command: "influx -execute 'CREATE DATABASE \"{{item.db_name}}\"'"
  with_items:
    - { db_name: '{{ influxdb_opentsdb_database }}' }
  changed_when: false

- name: Create InfluxDB user
  command: "influx -execute \"CREATE USER {{item.user}} WITH PASSWORD '{{item.pass}}' WITH ALL PRIVILEGES\""
  with_items:
    - { user: '{{ influxdb_admin_user_name }}', pass: '{{ influxdb_admin_user_password }}' }
  changed_when: false

- name: Set authentication over HTTP/HTTPs
  replace:
    regexp: '^(\s+auth-enabled\s+=\s+).*'
    replace:  '\1{{ influxdb_http_auth_enabled | lower }}'
    path: /etc/influxdb/influxdb.conf
  notify: influxdb restarted
